### ISSUE TITLE
2.2 POS checkout, cannot access normal checkout

### ISSUE THREAD

**Issue by seansan** [Adyen/magento#192] opened 2015-01-30 12:30 UTC
After trying to select POS checkout in CART

and after not succeeding 

we continue to normal checkout

The address page is then empty

![image](https://cloud.githubusercontent.com/assets/652395/5975671/0bc41742-a884-11e4-84b4-596666b89476.png)

**Comment by adyenpayments** [comment] 2015-01-30 14:02
HI Sean,

Discuss this issue over the phone. I am going to check if I can reproduce the issues you have.
Keep you updated.

Regards,
Rik

**Comment by seansan** [comment] 2015-01-31 13:05
Just something that I thought of: could it have something to do with persistent cart?

**Comment by adyenpayments** [comment] 2015-02-02 09:54
Hi Sean,

What do you mean exactly with persistent cart?

I can't reproduce this issue. I did the following checks:
1. clean install, installation through Magento Connect
2. Clean install, installation through GitHub
3. Upgrade version with installation with new version of GitHub

These three did not cause any issues. 
The only thing I can advise you is create a copy of your server and copy this to a test environment so you can do some test and debug the system. Maybe you have some conflicts between other modules.

Regards,
Adyen

**Comment by adyenpayments** [comment] 2015-02-02 10:01
Hi Sean,

See in the other issue that you are using modman in your live environment that is not something I recomment to do. The modman file has changed so you should update your modman with the command: $ modman update mymodule .  I recomment to use modman only in your development environment, on you live environment you should use the latest version of GitHub or Magento Connect. Could be that it now conflict with your modman checkout, because modman makes system links to files that are located in your modman directory.

Regards,
Adyen

**Comment by seansan** [comment] 2015-02-02 10:08
sorry this last comment is not clear

We use modman to pull the latest version of GitHub

We did this because the latest version of Magento Connect caused errors and
had to try something else (per request Rik)

**Comment by seansan** [comment] 2015-02-02 10:10
Also I would change the package name in modman. Now it reads "magento" this should be Adyen_Magento ... similar to the naming conventions used by other modules

![image](https://cloud.githubusercontent.com/assets/652395/5998831/1148fc38-aacc-11e4-9155-1233dd74e8ce.png)

**Comment by seansan** [comment] 2015-05-18 09:53
We are trying to update again. Only difference between PROD and DEV is the exclusion of these tables. So thet data within may trigger the error above ... 

Keep you updated

 ``` Dump MySQL Database


No-data export for: catalogsearch_fulltext catalogsearch_query catalogsearch_result core_session customer_address_entity customer_address_entity_datetime customer_address_entity_decimal customer_address_entity_int customer_address_entity_text customer_address_entity_varchar customer_entity customer_entity_datetime customer_entity_decimal customer_entity_int customer_entity_text customer_entity_varchar dataflow_batch dataflow_batch_export dataflow_batch_import dataflow_import_data dataflow_session log_url log_url_info log_visitor log_visitor_info log_visitor_online newsletter_problem newsletter_queue newsletter_queue_link newsletter_queue_store_link newsletter_subscriber newsletter_template report_compared_product_index report_event report_viewed_product_aggregated_daily report_viewed_product_aggregated_monthly report_viewed_product_aggregated_yearly report_viewed_product_index sales_bestsellers_aggregated_daily sales_bestsellers_aggregated_monthly sales_bestsellers_aggregated_yearly sales_flat_creditmemo sales_flat_creditmemo_comment sales_flat_creditmemo_grid sales_flat_creditmemo_item sales_flat_invoice sales_flat_invoice_comment sales_flat_invoice_grid sales_flat_invoice_item sales_flat_order sales_flat_order_address sales_flat_order_grid sales_flat_order_item sales_flat_order_payment sales_flat_order_status_history sales_flat_quote sales_flat_quote_address sales_flat_quote_address_item sales_flat_quote_item sales_flat_quote_item_option sales_flat_quote_payment sales_flat_quote_shipping_rate sales_flat_shipment sales_flat_shipment_comment sales_flat_shipment_grid sales_flat_shipment_item sales_flat_shipment_track sales_order_aggregated_created sales_order_aggregated_updated sales_order_tax sales_order_tax_item sales_payment_transaction sales_recurring_profile sales_recurring_profile_order sales_refunded_aggregated sales_refunded_aggregated_order```

**Comment by rikterbeek** [comment] 2015-06-04 09:41
Hi Sean,

I am closing this issue because I don't think it is a issue in our module.

Regards,
Rik
Adyen

**Closed by rikterbeek** 2015-06-04 09:41 UTC
