### ISSUE TITLE
It seems that notifications that use HMAC keys have problems sending trough notifications

### ISSUE THREAD

**Issue by paales** [Adyen/magento#250] opened 2015-03-24 09:45 UTC
Hi Rik, we spoke earlier on the phone about this (yesterday).

After setting up the notifications from scratch, all the notifications come through as expected. The only difference between the old notification and the new one is that the new one doesn't use the extra HMAC security key.

**Comment by rikterbeek** [comment] 2015-03-24 10:17
Hi Paul,

Why did you set this up for the old one ? We have introduced HMAC security key for merchant that having trouble with HTTP AUTHENTICATION and can use this instead of username/password validation. It is possible to do both but you don't see the HMAC key that is generated before because of security.

Regards,
RIk

**Comment by rikterbeek** [comment] 2015-04-08 06:40
Hi Paul,

I think the issue is resolved using a new notification setup without the HMAC security key. So i am closing this issue.

Regards,
Rik

**Comment by paales** [comment] 2015-04-08 09:14
> It is possible to do both
The notification doesn't work when enabling both, that was the bugreport.

**Comment by rikterbeek** [comment] 2015-04-09 10:39
Hi Paul,

Sorry, I see what you mean. I could reproduce the problem we will fix it.

Regards,
Rik
Adyen

**Comment by rikterbeek** [comment] 2015-04-16 09:36
Hi Paul,

It is an issue on the Adyen Platform this will be fixed on our side.

Regards,

**Closed by rikterbeek** 2015-04-16 09:36 UTC
