### ISSUE TITLE
Error when using Client Side Encryption in Admin

### ISSUE THREAD

**Issue by maximinimus** [Adyen/magento#263] opened 2015-04-15 08:46 UTC
Hi,

There is an error when you use Client-Side encryption in the Admin area as soon as you add a product to the quote you get the following fatal error:
Fatal error:  Call to a member function getStoreId() on a non-object in app/code/community/Adyen/Payment/Model/Adyen/Cc.php on line 121

I have fixed this in my local copy:

if (!is_object($this->_order)) {
                $storeId = Mage::getSingleton('adminhtml/session_quote')->getQuote()->getStoreId();
            } else {
                $storeId = $this->_order->getStoreId();
            }

**Comment by rikterbeek** [comment] 2015-04-15 12:49
Hi Mathew,

I could not reproduce this. What version of the module are you using? If you look in the latest version there is already a check for this see: 
https://github.com/Adyen/magento/blob/develop-2.3.0/app/code/community/Adyen/Payment/Model/Adyen/Cc.php#L142

Regards,
Rik
Adyen

**Comment by maximinimus** [comment] 2015-04-15 12:51
Rik,

Thanks, we are using 2.1.2.3 as we haven't upgraded to the latest version yet.

**Comment by rikterbeek** [comment] 2015-04-15 12:58
Hi Mathew,

Then that is the issue. It is fixed in the latest  stable release 2.2.2.

Regards,
Rik
Adyen

**Closed by rikterbeek** 2015-04-15 12:58 UTC
